[features]
seeds = false
skip-lint = false
[programs.localnet]
token_distributor = "HcM41aMorQuxwoGqYhV3Qtt63M8Q1Cu5JpEPca7MZ3MY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sangeet/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.28.0"